model_list:
    - litellm_params:
        api_base: https://llm-inference.internal.angelone.in/v1/messages
        api_key: sk--d-AWAtSYtikG7GvpvGNkw
        model: anthropic/*
      model_name: '*'
    - litellm_params:
        api_base: https://llm-inference.internal.angelone.in/v1
        api_key: sk--d-AWAtSYtikG7GvpvGNkw
        model: anthropic/claude-haiku-4-5
      model_name: claude-haiku-4-5
    - litellm_params:
        api_base: https://llm-inference.internal.angelone.in/v1
        api_key: sk--d-AWAtSYtikG7GvpvGNkw
        model: anthropic/claude-opus-4-7
      model_name: claude-opus-4-7
    - litellm_params:
        api_base: https://llm-inference.internal.angelone.in/v1
        api_key: sk--d-AWAtSYtikG7GvpvGNkw
        model: anthropic/claude-sonnet-4-6
      model_name: claude-sonnet-4-6
    - litellm_params:
        api_base: https://test.example.com/v1
        api_key: test-key-123
        model: test-model
      model_name: test-model
