apiVersion: v2
name: api-gateway
description: A1 Agent Engine - API Gateway
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: a1-lib
    version: "0.1.0"
    repository: "file://../../_lib"
