{{- define "lib.service" -}}
{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lib.fullname" . }}
  labels:
    {{- include "lib.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default .Values.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lib.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
