#!/bin/sh
# LiteLLM startup script that loads config file

# Wait for config file to exist (it will be generated by admin-api)
for i in $(seq 1 30); do
    if [ -f /etc/litellm/config.yaml ]; then
        echo "Config file found, starting litellm..."
        break
    fi
    echo "Waiting for config file... ($i/30)"
    sleep 1
done

# Start litellm with config file
/app/.venv/bin/litellm \
    --config /etc/litellm/config.yaml \
    --port 4000 \
    --debug
