image:
  tag: "placeholder"

replicaCount: 1

config:
  LOG_LEVEL: "debug"

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

hpa:
  enabled: false

ingress:
  enabled: false
