apiVersion: v2
name: agent-registry
description: A1 Agent Engine - Agent Registry
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: a1-lib
    version: "0.1.0"
    repository: "file://../../_lib"
